### ISSUE TITLE
how to use with async

### ISSUE THREAD

**Issue by nielsvanhooy** [scrapli/scrapli_replay#64]
hi dear.
i tried the Quick Start Guide with sync and that recorded wonderfully.
now i wanted to try it with async. but im not sure if im doing this right.

i tried various combinations:

this one gives: async def function and nog plugin installed
and an file test_something_else.yaml but with only {} in it

@pytest.mark.scrapli_replay
async def test_something_else():
        async with AsyncIOSXEDriver(**device) as conn:
            result = await conn.send_command("show run | i hostname")

this version gives back:  async def cuntion and no async plugin installed (i have pytest-asyncio installed)
@pytest.mark.async_scrapli_replay
async def test_something_else():
        async with AsyncIOSXEDriver(**device) as conn:
            result = await conn.send_command("show run | i hostname")

This one runs but gives no file back.
@pytest.mark.asyncio
@pytest.mark.async_scrapli_replay
async def test_something_else():
        async with AsyncIOSXEDriver(**device) as conn:
            result = await conn.send_command("show run | i hostname")

i couldnt really distill from the docs what im doing wrong so hoping for some feedback.
kind regards,

**Comment by carlmontanari** [comment]
```
import pytest

from scrapli.driver.core import AsyncIOSXEDriver


MY_DEVICE = {
    "host": "somehost",
    "transport": "asyncssh"
}

@pytest.mark.scrapli_replay
async def test_something_else():
    async with AsyncIOSXEDriver(**MY_DEVICE) as conn:
        result = await conn.send_command("show run | i hostname")

```

With the following in pyrpoject.toml to tell pytest to use auto async mode:

```
[tool.pytest.ini_options]
asyncio_mode = "auto"
```

Works as expected for me.

**Comment by nielsvanhooy** [comment]
Dear,

ill close this issue.
the pyproject part made it work for me :)
thanks!
